language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install
  - wget http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz -P data/
  - gunzip -f data/GeoLiteCity.dat.gz

script: phpunit --configuration tests/
